#!/bin/sh

DIR=`dirname $0`
BASE=`basename $0`
while :; do
  cd "$DIR"
  [ -L "$DIR/$BASE" ] || break
  DIR=`dirname "$(readlink $DIR/$BASE)"`
done

for OPT in "$@"; do
  case "$OPT" in
    --install )
      [ -L ~/.local/bin/sandbox ] || ln -s `pwd`/sandbox ~/.local/bin/sandbox
      exit
      ;;
    -l )
      cd boxes/
      find * -type d
      exit
      ;;
    -v )
      [ -n "$VOLUMES" ] && VOLUMES="$VOLUMES "
      VOLUMES="${VOLUMES}$2"
      shift 2
      ;;
  esac
done

BOX="$1"
SERVICE=`echo $BOX|tr \/ _`
export uid
export USER
export HOME
[ -z "$uid" ] && uid=$(id -u)
clean=1
WORKDIR="./volumes/work/${BOX}"

mkdir -p "$WORKDIR"
if [ -f "boxes/$BOX/Dockerfile" ]; then
  erb box="$BOX" -T- boxes/Dockerfile.erb > "boxes/$BOX/Dockerfile-user"
  erb box="$BOX" stage=build volumes="$VOLUMES" -T- boxes/docker-compose.yml.erb | docker-compose -f - build || fail
  erb box="$BOX" stage=up    volumes="$VOLUMES" -T- boxes/docker-compose.yml.erb | docker-compose -f - up -d run-"$SERVICE" 2>&1| grep "up-to-date$" && clean=0
  docker exec -it sandbox_run-"$SERVICE"_1 bash -l
  [ $clean = 1 ] || exit
  erb box="$BOX" stage=down  volumes="$VOLUMES" -T- boxes/docker-compose.yml.erb | docker-compose -f - down
  exit
fi

if [ -f "boxes/$BOX/vagrant_config.rb" ]; then
  export VAGRANT_CWD="$WORKDIR"
  [ "$(vagrant status|sed -ne '3s/^[^ ]* *\([^ ]*\).*/\1/p')" = running ] && clean=0
  [ $clean = 1 ] && erb box="$BOX" volumes="$VOLUMES" -T- boxes/Vagrantfile.erb > "$VAGRANT_CWD/Vagrantfile"
  [ $clean = 1 ] && vagrant up
  vagrant ssh
  [ $clean = 1 ] && vagrant halt
  exit
fi
