#!/bin/sh

if [ -z "$SANDBOX_WORKDIR" ]; then
  SANDBOX_WORKDIR=`pwd`
fi
if [ -z "$SANDBOX_ROOT" ]; then
  SANDBOX_ROOT=~/.sandbox
fi
if [ -z "$SANDBOX_PROFILE" ]; then
  SANDBOX_PROFILE="$SANDBOX_ROOT/profile"
fi
if [ -z "$SANDBOXES_DIR" ]; then
  SANDBOXES_DIR=./boxes
fi
if [ -z "$SANDBOX_VOLUME_DIR" ]; then
  SANDBOX_VOLUMES_DIR="$SANDBOX_ROOT/volumes"
fi

DIR=`dirname $0`
BASE=`basename $0`
while :; do
  cd "$DIR"
  [ -L "$DIR/$BASE" ] || break
  DIR=`dirname "$(readlink $DIR/$BASE)"`
done

[ -f "$SANDBOX_PROFILE" ] && . "$SANDBOX_PROFILE"

for OPT in "$@"; do
  case "$OPT" in
    --install )
      [ -L ~/.local/bin/sandbox ] || ln -s `pwd`/sandbox ~/.local/bin/sandbox
      exit
      ;;
    -l )
      cd "$SANDBOXES_DIR"
      find * -type d
      exit
      ;;
    -L )
      cd "$SANDBOXES_DIR"
      find * -type d|ruby -pe '$_ = "#{"  " * $_.count("/")}* #$_"'
      exit
      ;;
    -v )
      [ -n "$VOLUMES" ] && VOLUMES="$VOLUMES "
      VOLUMES="${VOLUMES}$2"
      shift 2
      ;;
  esac
done

SERVICE=`echo "$1"|tr \/ -`
export uid
export USER
export HOME
[ -z "$uid" ] && uid=$(id -u)
clean=1

if [ -z "$SANDBOX_HOME_DIR" ]; then
  SANDBOX_HOME_DIR="$SANDBOX_WORKDIR/.sandbox/$SERVICE/home"
fi
mkdir -p "$SANDBOX_HOME_DIR/$USER"
BOXES=""
for BOX_PART in $(echo "$1"|sed -e "s/\// /g"); do
  if [ -z "$BOXES" ]; then
    if [ -d "$SANDBOXES_DIR/$BOX_PART" ]; then
      BOXES="$SANDBOXES_DIR/$BOX_PART"
      BOX="$SANDBOXES_DIR/$BOX_PART"
    fi
  else
    for QUEUED_BOX in $BOXES; do
      if [ -d "$QUEUED_BOX/$BOX_PART" ]; then
        BOXES="$BOXES $QUEUED_BOX/$BOX_PART"
      fi
    done
  fi
done

if [ -f "$BOX/sandbox" ]; then
  . "$BOX/sandbox"
fi
