#!/bin/sh

if [ -z "$SANDBOX_WORKDIR" ]; then
  SANDBOX_WORKDIR=`pwd`
fi
if [ -z "$SANDBOX_ROOT" ]; then
  SANDBOX_ROOT=~/.sandbox
fi
if [ -z "$SANDBOX_PROFILE" ]; then
  SANDBOX_PROFILE="$SANDBOX_ROOT/profile"
fi
if [ -z "$SANDBOXES_DIR" ]; then
  SANDBOXES_DIR=./boxes
fi
if [ -z "$SANDBOX_VOLUME_DIR" ]; then
  SANDBOX_VOLUMES_DIR="$SANDBOX_ROOT/volumes"
fi

DIR=`dirname $0`
BASE=`basename $0`
while :; do
  cd "$DIR"
  [ -L "$DIR/$BASE" ] || break
  DIR=`dirname "$(readlink $DIR/$BASE)"`
done

[ -f "$SANDBOX_PROFILE" ] && . "$SANDBOX_PROFILE"

for OPT in "$@"; do
  case "$OPT" in
    --install ) # install `sandbox` command
      [ -d ~/.local/bin ] || mkdir ~/.local/bin
      [ -L ~/.local/bin/sandbox ] || ln -s `pwd`/sandbox ~/.local/bin/sandbox
      exit
      ;;
    -h ) # show this help
      echo "Usage: $BASE [options] sandbox-name"
      cat "$BASE"|sed -ne '/^for OPT in/,/^done/s/^ *\(-[^ )]*\) ) # \(.*\)/\1         \2/p'|sed -e 's/^\(.\{9\}\) */  \1 /g'
      exit
      ;;
    -l ) # list sandboxes
      cd "$SANDBOXES_DIR"
      find * -type d|sort
      exit
      ;;
    -L ) # pretty-print sandboxes
      cd "$SANDBOXES_DIR"
      find * -type d|sort|ruby -pe '$_ = "#{"  " * $_.count("/")}* #$_"'
      exit
      ;;
    -H ) # set /home/ directory of sandbox
      SANDBOX_HOME_DIR="$1"
      shift 2
      ;;
    -v ) # specify volume(s)
      [ -n "$VOLUMES" ] && VOLUMES="$VOLUMES "
      VOLUMES="${VOLUMES}$(
        cd "$SANDBOX_WORKDIR"
        IFS=":"
        set -- $2
        cd "$1"
        echo "$(pwd):$2"
      )"
      shift 2
      ;;
  esac
done

SERVICE=`echo "$1"|tr \/ -`
export uid
export USER
export HOME
[ -z "$uid" ] && uid=$(id -u)
clean=1

if [ -z "$SANDBOX_HOME_DIR" ]; then
  SANDBOX_HOME_DIR="$SANDBOX_WORKDIR/.sandbox/$SERVICE/home"
fi
mkdir -p "$SANDBOX_HOME_DIR/$USER"
BOXES=""
for BOX_PART in $(echo "$1"|sed -e "s/\// /g"); do
  if [ -z "$BOXES" ]; then
    if [ -d "$SANDBOXES_DIR/$BOX_PART" ]; then
      BOXES="$SANDBOXES_DIR/$BOX_PART"
      BOX="$SANDBOXES_DIR/$BOX_PART"
    fi
  else
    for QUEUED_BOX in $BOXES; do
      if [ -d "$QUEUED_BOX/$BOX_PART" ]; then
        BOXES="$BOXES $QUEUED_BOX/$BOX_PART"
      fi
    done
  fi
done
shift 1

if [ -f "$BOX/sandbox" ]; then
  . "$BOX/sandbox" "$@"
fi
