RUN apk add --no-cache \
  autoconf bison ca-certificates coreutils dpkg-dev dpkg \
  gcc gdbm-dev glib-dev libc-dev libffi-dev libressl libressl-dev \
  libxml2-dev libxslt-dev linux-headers make ncurses-dev procps readline-dev \
  ruby tar xz yaml-dev zlib-dev
